version: "2"

services:
  influxdb:
    image: influxdb
    container_name: local-influxdb  #grafanaからアクセスするための名前
    volumes:
      - /home/hazuki/docker/grafana/influxdb:/var/lib/influxdb
      - /home/hazuki/docker/grafana/.env:/tmp/.env  # .envファイルをコンテナにマウント
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_USER=${INFLUXDB_USERNAME} #.env fileからユーザー名を取得
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD} #.env fileからパスワードを取得
      - INFLUXDB_DB=data_all_result #使用するデータベース名

  grafana:
    image: grafana/grafana:7.1.1
    ports:
      - 8085:3000 #grafanaのポート
    user: "472"
    volumes:
      - /home/hazuki/docker/grafana/grafana:/var/lib/grafana    
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=admin
